# Cluster settings used by simple-experiments.

[project]
name = "rl-jax"
src_dirs = ["src"]
post_sync = "scripts/install_ale_wheel.sh"

[cluster]
host = "vulcan"
root = "$adam/rl-jax"
account = "aip-mbowling"

[venvs]
cpu = []
gpu = ["cuda", "atari"]

# default slurm settings.
[slurm]
time = "01:00:00"
cpus_per_task = 4
mem_per_cpu = "4G"
